[typesetting]

[formal_language_1]

[formal_language_1_presentation_1]
connective.symbol = "asterisk_operator"

[propositional_logic_1]

[propositional_logic_1_presentation_1]
conjunction.symbol = "wedge"
disjunction.symbol = "vee"
material_implication.symbol = "material_conditional"
# material_implication.symbol = "rightwards_arrow_double_short" # alternative
# material_implication.symbol = "rightwards_arrow_double_long" # alternative
negation.symbol = "not_sign"
# negation.symbol = "tilde" # alternative

[symbols]

# Mathematical Alphabets
# References:
#  - https://en.wikipedia.org/wiki/Mathematical_operators_and_symbols_in_Unicode

# Uppercase Serif Italic
# LaTeX Math
a_uppercase_serif_italic.latex_math = "\\textit{A}"
b_uppercase_serif_italic.latex_math = "\\textit{B}"
c_uppercase_serif_italic.latex_math = "\\textit{C}"
d_uppercase_serif_italic.latex_math = "\\textit{D}"
e_uppercase_serif_italic.latex_math = "\\textit{E}"
f_uppercase_serif_italic.latex_math = "\\textit{F}"
g_uppercase_serif_italic.latex_math = "\\textit{G}"
h_uppercase_serif_italic.latex_math = "\\textit{H}"
i_uppercase_serif_italic.latex_math = "\\textit{I}"
j_uppercase_serif_italic.latex_math = "\\textit{J}"
k_uppercase_serif_italic.latex_math = "\\textit{K}"
l_uppercase_serif_italic.latex_math = "\\textit{L}"
m_uppercase_serif_italic.latex_math = "\\textit{M}"
n_uppercase_serif_italic.latex_math = "\\textit{N}"
o_uppercase_serif_italic.latex_math = "\\textit{O}"
p_uppercase_serif_italic.latex_math = "\\textit{P}"
q_uppercase_serif_italic.latex_math = "\\textit{Q}"
r_uppercase_serif_italic.latex_math = "\\textit{R}"
s_uppercase_serif_italic.latex_math = "\\textit{S}"
t_uppercase_serif_italic.latex_math = "\\textit{T}"
u_uppercase_serif_italic.latex_math = "\\textit{U}"
v_uppercase_serif_italic.latex_math = "\\textit{V}"
w_uppercase_serif_italic.latex_math = "\\textit{W}"
x_uppercase_serif_italic.latex_math = "\\textit{X}"
y_uppercase_serif_italic.latex_math = "\\textit{Y}"
z_uppercase_serif_italic.latex_math = "\\textit{Z}"
# Unicode Extended
a_uppercase_serif_italic.unicode_extended = "𝐴"
b_uppercase_serif_italic.unicode_extended = "𝐵"
c_uppercase_serif_italic.unicode_extended = "𝐶"
d_uppercase_serif_italic.unicode_extended = "𝐷"
e_uppercase_serif_italic.unicode_extended = "𝐸"
f_uppercase_serif_italic.unicode_extended = "𝐹"
g_uppercase_serif_italic.unicode_extended = "𝐺"
h_uppercase_serif_italic.unicode_extended = "𝐻"
i_uppercase_serif_italic.unicode_extended = "𝐼"
j_uppercase_serif_italic.unicode_extended = "𝐽"
k_uppercase_serif_italic.unicode_extended = "𝐾"
l_uppercase_serif_italic.unicode_extended = "𝐿"
m_uppercase_serif_italic.unicode_extended = "𝑀"
n_uppercase_serif_italic.unicode_extended = "𝑁"
o_uppercase_serif_italic.unicode_extended = "𝑂"
p_uppercase_serif_italic.unicode_extended = "𝑃"
q_uppercase_serif_italic.unicode_extended = "𝑄"
r_uppercase_serif_italic.unicode_extended = "𝑅"
s_uppercase_serif_italic.unicode_extended = "𝑆"
t_uppercase_serif_italic.unicode_extended = "𝑇"
u_uppercase_serif_italic.unicode_extended = "𝑈"
v_uppercase_serif_italic.unicode_extended = "𝑉"
w_uppercase_serif_italic.unicode_extended = "𝑊"
x_uppercase_serif_italic.unicode_extended = "𝑋"
y_uppercase_serif_italic.unicode_extended = "𝑌"
z_uppercase_serif_italic.unicode_extended = "𝑍"
# Unicode Limited
a_uppercase_serif_italic.unicode_limited = "A"
b_uppercase_serif_italic.unicode_limited = "B"
c_uppercase_serif_italic.unicode_limited = "C"
d_uppercase_serif_italic.unicode_limited = "D"
e_uppercase_serif_italic.unicode_limited = "E"
f_uppercase_serif_italic.unicode_limited = "F"
g_uppercase_serif_italic.unicode_limited = "G"
h_uppercase_serif_italic.unicode_limited = "H"
i_uppercase_serif_italic.unicode_limited = "I"
j_uppercase_serif_italic.unicode_limited = "J"
k_uppercase_serif_italic.unicode_limited = "K"
l_uppercase_serif_italic.unicode_limited = "L"
m_uppercase_serif_italic.unicode_limited = "M"
n_uppercase_serif_italic.unicode_limited = "N"
o_uppercase_serif_italic.unicode_limited = "O"
p_uppercase_serif_italic.unicode_limited = "P"
q_uppercase_serif_italic.unicode_limited = "Q"
r_uppercase_serif_italic.unicode_limited = "R"
s_uppercase_serif_italic.unicode_limited = "S"
t_uppercase_serif_italic.unicode_limited = "T"
u_uppercase_serif_italic.unicode_limited = "U"
v_uppercase_serif_italic.unicode_limited = "V"
w_uppercase_serif_italic.unicode_limited = "W"
x_uppercase_serif_italic.unicode_limited = "X"
y_uppercase_serif_italic.unicode_limited = "Y"
z_uppercase_serif_italic.unicode_limited = "Z"

# Uppercase Serif Italic Bold
# LaTeX Math
a_uppercase_serif_italic_bold.latex_math = "\\bm{\\textit{A}}"
b_uppercase_serif_italic_bold.latex_math = "\\bm{\\textit{B}}"
c_uppercase_serif_italic_bold.latex_math = "\\bm{\\textit{C}}"
d_uppercase_serif_italic_bold.latex_math = "\\bm{\\textit{D}}"
e_uppercase_serif_italic_bold.latex_math = "\\bm{\\textit{E}}"
f_uppercase_serif_italic_bold.latex_math = "\\bm{\\textit{F}}"
g_uppercase_serif_italic_bold.latex_math = "\\bm{\\textit{G}}"
h_uppercase_serif_italic_bold.latex_math = "\\bm{\\textit{H}}"
i_uppercase_serif_italic_bold.latex_math = "\\bm{\\textit{I}}"
j_uppercase_serif_italic_bold.latex_math = "\\bm{\\textit{J}}"
k_uppercase_serif_italic_bold.latex_math = "\\bm{\\textit{K}}"
l_uppercase_serif_italic_bold.latex_math = "\\bm{\\textit{L}}"
m_uppercase_serif_italic_bold.latex_math = "\\bm{\\textit{M}}"
n_uppercase_serif_italic_bold.latex_math = "\\bm{\\textit{N}}"
o_uppercase_serif_italic_bold.latex_math = "\\bm{\\textit{O}}"
p_uppercase_serif_italic_bold.latex_math = "\\bm{\\textit{P}}"
q_uppercase_serif_italic_bold.latex_math = "\\bm{\\textit{Q}}"
r_uppercase_serif_italic_bold.latex_math = "\\bm{\\textit{R}}"
s_uppercase_serif_italic_bold.latex_math = "\\bm{\\textit{S}}"
t_uppercase_serif_italic_bold.latex_math = "\\bm{\\textit{T}}"
u_uppercase_serif_italic_bold.latex_math = "\\bm{\\textit{U}}"
v_uppercase_serif_italic_bold.latex_math = "\\bm{\\textit{V}}"
w_uppercase_serif_italic_bold.latex_math = "\\bm{\\textit{W}}"
x_uppercase_serif_italic_bold.latex_math = "\\bm{\\textit{X}}"
y_uppercase_serif_italic_bold.latex_math = "\\bm{\\textit{Y}}"
z_uppercase_serif_italic_bold.latex_math = "\\bm{\\textit{Z}}"
# Unicode Extended
a_uppercase_serif_italic_bold.unicode_extended = "𝑨"
b_uppercase_serif_italic_bold.unicode_extended = "𝑩"
c_uppercase_serif_italic_bold.unicode_extended = "𝑪"
d_uppercase_serif_italic_bold.unicode_extended = "𝑫"
e_uppercase_serif_italic_bold.unicode_extended = "𝑬"
f_uppercase_serif_italic_bold.unicode_extended = "𝑭"
g_uppercase_serif_italic_bold.unicode_extended = "𝑮"
h_uppercase_serif_italic_bold.unicode_extended = "𝑯"
i_uppercase_serif_italic_bold.unicode_extended = "𝑰"
j_uppercase_serif_italic_bold.unicode_extended = "𝑱"
k_uppercase_serif_italic_bold.unicode_extended = "𝑲"
l_uppercase_serif_italic_bold.unicode_extended = "𝑳"
m_uppercase_serif_italic_bold.unicode_extended = "𝑴"
n_uppercase_serif_italic_bold.unicode_extended = "𝑵"
o_uppercase_serif_italic_bold.unicode_extended = "𝑶"
p_uppercase_serif_italic_bold.unicode_extended = "𝑷"
q_uppercase_serif_italic_bold.unicode_extended = "𝑸"
r_uppercase_serif_italic_bold.unicode_extended = "𝑹"
s_uppercase_serif_italic_bold.unicode_extended = "𝑺"
t_uppercase_serif_italic_bold.unicode_extended = "𝑻"
u_uppercase_serif_italic_bold.unicode_extended = "𝑼"
v_uppercase_serif_italic_bold.unicode_extended = "𝑽"
w_uppercase_serif_italic_bold.unicode_extended = "𝑾"
x_uppercase_serif_italic_bold.unicode_extended = "𝑿"
y_uppercase_serif_italic_bold.unicode_extended = "𝒀"
z_uppercase_serif_italic_bold.unicode_extended = "𝒁"
# Unicode Limited
a_uppercase_serif_italic_bold.unicode_limited = "bold-A"
b_uppercase_serif_italic_bold.unicode_limited = "bold-B"
c_uppercase_serif_italic_bold.unicode_limited = "bold-C"
d_uppercase_serif_italic_bold.unicode_limited = "bold-D"
e_uppercase_serif_italic_bold.unicode_limited = "bold-E"
f_uppercase_serif_italic_bold.unicode_limited = "bold-F"
g_uppercase_serif_italic_bold.unicode_limited = "bold-G"
h_uppercase_serif_italic_bold.unicode_limited = "bold-H"
i_uppercase_serif_italic_bold.unicode_limited = "bold-I"
j_uppercase_serif_italic_bold.unicode_limited = "bold-J"
k_uppercase_serif_italic_bold.unicode_limited = "bold-K"
l_uppercase_serif_italic_bold.unicode_limited = "bold-L"
m_uppercase_serif_italic_bold.unicode_limited = "bold-M"
n_uppercase_serif_italic_bold.unicode_limited = "bold-N"
o_uppercase_serif_italic_bold.unicode_limited = "bold-O"
p_uppercase_serif_italic_bold.unicode_limited = "bold-P"
q_uppercase_serif_italic_bold.unicode_limited = "bold-Q"
r_uppercase_serif_italic_bold.unicode_limited = "bold-R"
s_uppercase_serif_italic_bold.unicode_limited = "bold-S"
t_uppercase_serif_italic_bold.unicode_limited = "bold-T"
u_uppercase_serif_italic_bold.unicode_limited = "bold-U"
v_uppercase_serif_italic_bold.unicode_limited = "bold-V"
w_uppercase_serif_italic_bold.unicode_limited = "bold-W"
x_uppercase_serif_italic_bold.unicode_limited = "bold-X"
y_uppercase_serif_italic_bold.unicode_limited = "bold-Y"
z_uppercase_serif_italic_bold.unicode_limited = "bold-Z"

# Punctuation
# Brakets
close_parenthesis.latex_math = "\\right)"
close_parenthesis.unicode_extended = ")"
close_parenthesis.unicode_limited = ")"
open_parenthesis.latex_math = "\\left("
open_parenthesis.unicode_extended = "("
open_parenthesis.unicode_limited = "("
# Others
collection_separator.latex_math = ", "
collection_separator.unicode_extended = ", "
collection_separator.unicode_limited = ", "
space.latex_math = " "
space.unicode_extended = " "
space.unicode_limited = " "

# Formal languages symbols
asterisk_operator.latex_math = "\\ast"
asterisk_operator.unicode_extended = "∗"
asterisk_operator.unicode_limited = "*"

# Logic symbols
# references:
# - https://en.wikipedia.org/wiki/List_of_logic_symbols
rightwards_arrow_double_long.latex_math = "\\implies" # longer than \\Rightarrow
rightwards_arrow_double_long.unicode_extended = "⇒" # identical to short version
rightwards_arrow_double_long.unicode_limited = "==>"
rightwards_arrow_double_short.latex_math = "\\Rightarrow" # shorter than \\implies
rightwards_arrow_double_short.unicode_extended = "⇒" # identical to long version
rightwards_arrow_double_short.unicode_limited = "=>"
material_conditional.latex_math = "\\supset"
material_conditional.unicode_extended = "⊃"
material_conditional.unicode_limited = "implies"
not_sign.latex_math = "\\lnot"
not_sign.unicode_extended = "¬"
not_sign.unicode_limited = "¬"
rightwards_arrow.latex_math = "\\rightarrow"
rightwards_arrow.unicode_extended = "→"
rightwards_arrow.unicode_limited = "-->"
tilde.latex_math = "\\sim"
tilde.unicode_extended = "~"
tilde.unicode_limited = "~"
vee.latex_math = "\\lor"
vee.unicode_extended = "∨"
vee.unicode_limited = "or"
wedge.latex_math = "\\land"
wedge.unicode_extended = "∧"
wedge.unicode_limited = "and" # an alternative could be to use the "^" accent, but the symmetry with disjunction would be broken.
