import foundations
import greek_alphabet_lowercase_serif_italic as _greek_alphabet_lowercase_serif_italic

greek_alphabet_lowercase_serif_italic = _greek_alphabet_lowercase_serif_italic.GreekAlphabetLowercaseSerifItalic()
print(greek_alphabet_lowercase_serif_italic.alpha.configurations[0])
print(greek_alphabet_lowercase_serif_italic.phi.configurations[1])
print(greek_alphabet_lowercase_serif_italic.psi.configurations[2])
