import foundations
import greek_alphabet_lowercase_serif_italic as _greek_alphabet_lowercase_serif_italic
import greek_alphabet_uppercase_serif_italic as _greek_alphabet_uppercase_serif_italic

preferences = foundations.Preferences()

greek_alphabet_lowercase_serif_italic = _greek_alphabet_lowercase_serif_italic.GreekAlphabetLowercaseSerifItalic()
print(greek_alphabet_lowercase_serif_italic.alpha.configurations[0])
print(greek_alphabet_lowercase_serif_italic.phi.configurations[1])
print(greek_alphabet_lowercase_serif_italic.psi.configurations[2])

greek_alphabet_uppercase_serif_italic = _greek_alphabet_uppercase_serif_italic.GreekAlphabetUppercaseSerifItalic()
print(greek_alphabet_uppercase_serif_italic.alpha.configurations[0])
print(greek_alphabet_uppercase_serif_italic.phi.configurations[1])
print(greek_alphabet_uppercase_serif_italic.psi.configurations[2])

pass
