import punctilious.pu_20_01_greek_alphabet_lowercase_serif_italic as _greek_alphabet_lowercase_serif_italic
import punctilious.pu_20_02_greek_alphabet_uppercase_serif_italic as _greek_alphabet_uppercase_serif_italic
import punctilious.pu_20_03_latin_alphabet_lowercase_serif_bold as _latin_alphabet_lowercase_serif_bold
import punctilious.pu_20_04_latin_alphabet_lowercase_serif_italic as _latin_alphabet_lowercase_serif_italic
import punctilious.pu_20_05_latin_alphabet_uppercase_serif_italic as _latin_alphabet_uppercase_serif_italic

greek_alphabet_lowercase_serif_italic = _greek_alphabet_lowercase_serif_italic.font
greek_alphabet_uppercase_serif_italic = _greek_alphabet_uppercase_serif_italic.font
latin_alphabet_lowercase_serif_bold = _latin_alphabet_lowercase_serif_bold.font
latin_alphabet_lowercase_serif_italic = _latin_alphabet_lowercase_serif_italic.font
latin_alphabet_uppercase_serif_italic = _latin_alphabet_uppercase_serif_italic.font
